---
- name: Copy {{ sourcemod_plugin.name }} to the active folder
  copy:
    src: "{{ sourcemod_extra_plugins_directory }}/{{ sourcemod_plugin.name }}.smx"
    dest: "{{ __sourcemod_plugins_path }}/"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  when:
    - sourcemod_plugin.state is not defined
      or sourcemod_plugin.state == "enabled"

- name: Copy {{ sourcemod_plugin.name }} to the disabled folder
  copy:
    src: "{{ sourcemod_extra_plugins_directory }}/{{ sourcemod_plugin.name }}.smx"
    dest: "{{ __sourcemod_plugins_path }}/disabled/"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  when:
    - sourcemod_plugin.state is defined
    - sourcemod_plugin.state == "disabled"
