---
- name: Copy {{ sourcemod_plugin.name }} to the active folder
  copy:
    src: "{{ __sourcemod_plugins_path }}/disabled/{{ sourcemod_plugin.name }}.smx"
    dest: "{{ __sourcemod_plugins_path }}/"
    remote_src: yes
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: Remove {{ sourcemod_plugin.name }}
  file:
    path: "{{ __sourcemod_plugins_path }}/disabled/{{ sourcemod_plugin.name }}.smx"
    state: absent
